### ISSUE TITLE
Doesn't work with Rails 4.2

### ISSUE THREAD

**Issue by jmuheim** [markgandolfo/send-keys#14]
```
josh@Macbuech:~/Documents/Work/MuheimWebdesign/base/src (features/accessibility *)$ rake
/Users/josh/.rvm/gems/ruby-2.1.0@base/gems/send-keys-0.1.0/lib/send-keys/step_definitions/send_keys_steps.rb:10:in `<top (required)>': undefined method `And' for main:Object (NoMethodError)
    from /Users/josh/.rvm/gems/ruby-2.1.0@base/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
    from /Users/josh/.rvm/gems/ruby-2.1.0@base/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
    from /Users/josh/.rvm/gems/ruby-2.1.0@base/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /Users/josh/.rvm/gems/ruby-2.1.0@base/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
```
